version: "3"
services:
  go-server:
    build: ./go_server
    ports:
      - '8000:8000'
    volumes:
      - ./go_server:/app

  react-frontend:
    build: ./webfit_react
    ports:
        - '3000:3000'
    volumes:
        - ./webfit_react:/app
    stdin_open: true
